### ISSUE TITLE
Running stress tests causes exception 

### ISSUE THREAD

**Issue by pianetarosso** [filodb/FiloDB#121]
Hi, I've tried to run the stress tests, but I'm getting this exception:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/DataFrame
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:713)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.DataFrame
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 10 more
`

I think it's caused by the fact that I'm running it on Spark 2.0.0

**Comment by velvia** [comment]
First, are you running it within SBT or did you do the assembly?  Might not be able to run it within SBT.  

Second, no 2.0 support is not there yet.  It is on the list though of near-term things.

**Comment by velvia** [comment]
Will reverify this when upgrading to 2.0

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.
